name: Daily Business Listings Automation

on:
  schedule:
    - cron: "0 2 * * *"    # 2 AM UTC daily
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --upgrade \
            requests curl-cffi==0.7.3 supabase==2.8.1 colorama==0.4.6 python-dotenv==1.0.1

      - name: Run daily scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          MAX_PAGES: "500"
          WORKERS: "5"
        run: python daily_scraper.py
