# .github/workflows/cleaning-scraper.yml
name: Cleaning Listings Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"   # 2 AM UTC daily

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show script head
        run: |
          echo "HEAD:" && git rev-parse --short HEAD
          echo "Top of cleaning_scraper.py:"
          head -n 40 cleaning_scraper.py

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (no cache)
        run: |
          python -m pip install --upgrade pip
          pip install curl-cffi==0.7.3 colorama==0.4.6

      - name: Run scraper
        env:
          # Not strictly required for this cleaning-only scraper,
          # but leave here if you later push into Supabase.
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python cleaning_scraper.py
          echo "Artifacts:"
          ls -lah *.json *.csv || true
